export const ARTS_LIST_REQUEST = "ARTS_LIST_REQUEST";
export const ARTS_LIST_SUCCESS = "ARTS_LIST_SUCCESS";
export const ARTS_LIST_FAIL = "ARTS_LIST_FAIL";

export const ARTS_RANDOM_REQUEST = "ARTS_RANDOM_REQUEST";
export const ARTS_RANDOM_SUCCESS = "ARTS_RANDOM_SUCCESS";
export const ARTS_RANDOM_FAIL = "ARTS_RANDOM_FAIL";

export const ART_DETAILS_REQUEST = "ART_DETAILS_REQUEST";
export const ART_DETAILS_SUCCESS = "ART_DETAILS_SUCCESS";
export const ART_DETAILS_FAIL = "ART_DETAILS_FAIL";
export const ART_DETAILS_RESET = "ART_DETAILS_RESET";

export const ART_TOP_RATED_REQUEST = "ART_TOP_RATED_REQUEST";
export const ART_TOP_RATED_SUCCESS = "ART_TOP_RATED_SUCCESS";
export const ART_TOP_RATED_FAIL = "ART_TOP_RATED_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const DELETE_ART_REQUEST = "DELETE_ART_REQUEST";
export const DELETE_ART_SUCCESS = "DELETE_ART_SUCCESS";
export const DELETE_ART_FAIL = "DELETE_ART_FAIL";

export const DELETE_ALL_ARTS_REQUEST = "DELETE_ALL_ARTS_REQUEST";
export const DELETE_ALL_ARTS_SUCCESS = "DELETE_ALL_ARTS_SUCCESS";
export const DELETE_ALL_ARTS_FAIL = "DELETE_ALL_ARTS_FAIL";

export const CREATE_ART_REQUEST = "CREATE_ART_REQUEST";
export const CREATE_ART_SUCCESS = "CREATE_ART_SUCCESS";
export const CREATE_ART_FAIL = "CREATE_ART_FAIL";
export const CREATE_ART_RESET = "CREATE_ART_RESET";

export const UPDATE_ART_REQUEST = "UPDATE_ART_REQUEST";
export const UPDATE_ART_SUCCESS = "UPDATE_ART_SUCCESS";
export const UPDATE_ART_FAIL = "UPDATE_ART_FAIL";
export const UPDATE_ART_RESET = "UPDATE_ART_RESET";
